export const accountsInitialState = {
  account: true,
  mt: true,
  balance: true,
  equity: true,
  equity_percent: true,
  open_traders: true,
  pending: true,
  day: true,
  week: true,
  month: true,
  total: true,
};

export const tradesInitialState = {
  id: true,
  ticket: true,
  account: true,
  opentime: true,
  symbol: true,
  type: true,
  lots: true,
  openprice: true,
  sl: true,
  tp: true,
  com: true,
  swap: true,
  profit: true,
};
export const historyInitialState = {
  id: true,
  ticket: true,
  account: true,
  opentime: true,
  symbol: true,
  type: true,
  lots: true,
  openprice: true,
  sl: true,
  tp: true,
  closetime: true,
  closeprice: true,
  com: true,
  swap: true,
  profit: true,
};
